@echo off

echo @echo off ^

rem generated by %~nx0 ^

 ^

setlocal ^

 ^

for /f "usebackq tokens=*" %%%%1 in (`where dart`) do ( ^

	set dart_cmd=%%%%1^

	set dart_dir=%%%%~dp1^

	goto exec ^

) ^

 ^

for /f "usebackq tokens=*" %%%%1 in (`where flutter`) do ( ^

	set dart_cmd=%%%%~dp1cache\dart-sdk\bin\dart.exe^

	set dart_dir=%%%%~dp1cache\dart-sdk\bin\^

	goto exec ^

) ^

 ^

:exec ^

 ^

if not exist "%%dart_cmd%%" exit /B 1^

if not exist "%%dart_dir%%" exit /B 1^

 ^

"%%dart_cmd%%" "%%dart_dir%%snapshots\analysis_server.dart.snapshot" %%* ^

> dart-analysis-server.cmd

echo completed
