#!/bin/bash

set -e

cat <<EOF >./dart-analysis-server
#!/bin/bash

# generated by `basename $0`

set -e
set -u

dart_cmd=\$(which dart 2>/dev/null) && :
dart_dir=

if [ -n "\$dart_cmd" ]; then
  dart_dir=\$(dirname \$dart_cmd)
else
  flutter_cmd=\$(which flutter 2>/dev/null) && :
  [ -n "\$flutter_cmd" ] && dart_cmd=\$(dirname \$flutter_cmd)/cache/dart-sdk/bin/dart
  [ -n "\$flutter_cmd" ] && dart_dir=\$(dirname \$flutter_cmd)/cache/dart-sdk/bin
fi

[ ! -f "\$dart_cmd" ] && exit 1
[ ! -d "\$dart_dir" ] && exit 1

"\$dart_cmd" "\$dart_dir/snapshots/analysis_server.dart.snapshot" "\$@"
EOF

chmod +x ./dart-analysis-server

echo completed
